# Generated by Django 5.1 on 2024-12-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
